<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOz0FlCb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOz0FlCb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOz0FlCb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOz0FlCb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOz0FlCb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oz0FlCb',
    'container.build_id' => '267f53a8',
    'container.build_time' => 1750255616,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOz0FlCb');
