<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW1MRgQP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW1MRgQP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW1MRgQP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW1MRgQP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW1MRgQP\App_KernelDevDebugContainer([
    'container.build_hash' => 'W1MRgQP',
    'container.build_id' => '82e4f3e0',
    'container.build_time' => 1750254910,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW1MRgQP');
